# State graph generated by ./write_sg 4.2 (compiled 15-Oct-03 at 3:06 PM)
# from </home/vale/Scaricati/iccad95/dff.g> on 26-Jul-18 at 9:29 PM
.model /home/vale/Scaricati/iccad95/dff.g
.inputs  phi D
.outputs  Q
.dummy  e
.state graph 
s13 e s14
s13 e s18
s12 e s13
s16 phi- s17
s16 D- s11
s8 phi+ s9
s6 D+ s1
s6 phi- s7
s3 e s4
s3 e s8
s2 e s3
s1 phi- s2
s19 Q- s0
s10 e s16
s11 phi- s12
s18 phi+ s19
s7 D+ s2
s4 D- s5
s0 e s6
s14 D+ s15
s5 D+ s3
s9 Q+ s10
s15 D- s13
s17 D- s12
.marking {s0}
.end
