# State graph generated by ./write_sg 4.2 (compiled 15-Oct-03 at 3:06 PM)
# from </home/vale/Scaricati/iccad95/pulse.g> on 26-Jul-18 at 9:31 PM
.model /home/vale/Scaricati/iccad95/pulse.g
.inputs  x1
.outputs  x2 x3
.state graph 
s5 x2+ s9
s0 x3- s3
s9 x1- s6
s7 x2- s2
s3 x1- s8
s4 x3+ s10
s8 x1+ s4
s6 x1+ s0
s1 x1+ s7
s11 x1+ s5
s10 x1- s1
s2 x1- s11
.marking {s0}
.end
